openapi: 3.0.0
info:
  description: This API receives from inventory check events from the RFID app
  version: "1.0.0"
  title: RFID API
  contact:
    email: rdevera6@my.bcit.ca
tags:
  - name: RFID
    description: RFID app features that counts and checks inventory
paths:
  /inventory/count:
    get:
      tags:
        - devices
      summary: gets inventory count
      operationId: app.get_inventory_count
      description: gets inventory count after timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: gets results starting from the start timestamp
          schema:
            type: string
            format: date-time
            example: 21-10-27 11:01:16Z
        - name: end_timestamp
          in: query
          description: gets results up until the end timestamp
          schema:
            type: string
            format: date-time
            example: 21-10-27 11:01:16Z
      responses:
        '200':
          description: successfuly returned a list of count events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryScan'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /inventory/checked:
    get:
      tags:
        - devices
      summary: gets scanned items
      operationId: app.get_checked_item
      description: gets checked items after timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: gets results starting from the start timestamp
          schema:
            type: string
            format: date-time
            example: 21-10-27 11:01:16Z
        - name: end_timestamp
          in: query
          description: gets results up until the end timestamp
          schema:
            type: string
            format: date-time
            example: 21-10-27 11:01:16Z
      responses:
        '200':
          description: successfuly returned a list of check events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CheckInOut'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    InventoryScan:
      required:
        - total_count
        - expected_count
        - items_missing
        - surplus
        - time_scanned
      properties:
        total_count:
          type: integer
          example: 731
        expected_count:
          type: integer
          example: 735
        items_missing:
          type: integer
          example: 4
        surplus:
          type: integer
          example: 0
        time_scanned:
          type: string
          format: date-time
          example: 2021-09-27-29T09:12:33.001Z
      type: object
    CheckInOut:
      required:
        - product_code
        - location
        - item_from
        - item_type
        - time_scanned
      properties:
        product_code:
          type: string
          example: MB-583955
        location:
          type: string
          example: stage room
        item_from:
          type: string
          example: back room
        item_type:
          type: string
          example: Men's Bottoms
        time_scanned:
          type: string
          format: date-time
          example: 2021-09-27-29T09:12:33.001Z
      type: object
